<!doctype html>
<html>
<head>
    <link rel="stylesheet" href="templates/main/index.css">
</head>
<body>
    <h1>Try to upload image...</h1>
    <div id="cam-photo"></div>
    <button class="take">Take and upload photo</button>
    <h2>The link will be below</h2>
    <div class="result">I am the link...</div>

    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="templates/main/cam.js"></script>
    <script src="templates/main/index.js"></script>
</body>
</html>
